version: "3"

services:
  mc:
    image: itzg/minecraft-server:java17-graalvm-ce
    stop_grace_period: 45s
    ports:
      - 25565:25565
      - 25575:25575
    environment:
      UID: 1001
      GID: 1002
      EULA: true
      JVM_OPTS: "-XX:+UseJVMCICompiler"
      MEMORY: "8G"
      USE_AIKAR_FLAGS: true
      TYPE: "AUTO_CURSEFORGE"
      DISABLE_HEALTHCHECK: true
      CF_SLUG: "all-of-fabric-6"
      CF_FILE_ID: 4419791
      MODRINTH_PROJECTS: "notenoughcrashes:release"
      STOP_SERVER_ANNOUNCE_DELAY: 30
      ONLINE_MODE: true
      MOTD: "\\u00A7c                     \\u00A7aArisu Kuma"
      ALLOW_FLIGHT: true
      DIFFICULTY: "hard"
      SPAWN_PROTECTION: 0
      LEVEL: "arisu"
      PVP: false
      SEED: "arisukuma"
      MAX_TICK_TIME: "-1"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - /etc/timezone:/etc/timezone:ro
      - /home/natsuki/cucraft:/data
      - /home/natsuki/optmods:/mods
